[book]
authors = ["DiskANN Rust Port Working Group"]
description = "A high-performance Rust implementation of the DiskANN approximate nearest neighbor search algorithm"
language = "en"
multilingual = false
src = "src"
title = "DiskANN Rust Implementation"

[rust]
edition = "2024"

[build]
build-dir = "book"
create-missing = true

[preprocessor.links]
# Enable cross-references between chapters

[output.html]
additional-css = ["theme/custom.css"]
git-repository-url = "https://github.com/atsentia/diskann-to-rust"
edit-url-template = "https://github.com/atsentia/diskann-to-rust/edit/main/DiskANNInRust/docs/{path}"
site-url = "https://atsentia.github.io/diskann-to-rust/"

[output.html.fold]
enable = true
level = 1

[output.html.search]
enable = true

[output.html.print]
enable = true
